name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macOS-swift-latest:
    name: macOS (Swift Latest)
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test -c debug
    - name: Test (Release)
      run: swift test -c release
    
  linux-swift-53:
    name: Linux x86_64 (Swift 5.5)
    runs-on: ubuntu-20.04
    container: swift:5.5-focal
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test -c debug
    - name: Test (Release)
      run: swift test -c release
    
  windows-swift-latest:
    name: Windows
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
         - tag: 5.5.3-RELEASE
           branch: swift-5.5.3-release
         - tag: DEVELOPMENT-SNAPSHOT-2022-02-03-a
           branch: development
           
    steps:
    - uses: compnerd/gha-setup-swift@main
      with:
        branch: ${{ matrix.branch }}
        tag: ${{ matrix.tag }}
    - uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test -c debug
    - name: Test (Release)
      run: swift test -c release
